import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import MainWrapper from "@/components/main/MainWrapper";
import LeftSideBar from "@/components/sidebar/Left.Sidebar";
import RightSideBar from "@/components/sidebar/Right.Sidebar";
import Header from "@/components/main/Header/Header";

const CustomFont = Manrope({
  subsets: ["latin"],
  weight: ["400", "700"],
});
export const metadata: Metadata = {
  title: "Ryan Bachtiar Abdalla | Developer Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${CustomFont.className} antialiased flex flex-col justify-center items-end h-screen`}
      >
        <ThemeProvider
          attribute={"class"}
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="flex flex-1 justify-center items-center w-full">
            <h1 className="hidden md:block text-sm font-semibold">
              Ryan Bachtiar Abdalla | Portofolio
            </h1>
          </div>
          <MainWrapper>
            <LeftSideBar />
            <div className="flex flex-col w-full h-full">
              <Header />
              {children}
            </div>
            <RightSideBar />
          </MainWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
